########################################################################
### EBAZEXT pin
########################################################################
set_property PACKAGE_PIN T19 [get_ports {pl_led0}]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_led0}]
set_property PACKAGE_PIN V20 [get_ports {pl_led1}]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_led1}]
set_property PACKAGE_PIN U19 [get_ports {pl_key0}]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_key0}]
set_property PACKAGE_PIN U20 [get_ports {pl_key1}]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_key1}]

set_property PACKAGE_PIN P19 [get_ports {cmos_pclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_pclk}]
set_property PACKAGE_PIN T20 [get_ports {cmos_sdat}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_sdat}]
set_property PACKAGE_PIN R18 [get_ports {cmos_sclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_sclk}]
set_property PACKAGE_PIN R19 [get_ports {cmos_href}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_href}]
set_property PACKAGE_PIN P20 [get_ports {cmos_xclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_xclk}]
set_property PACKAGE_PIN N17 [get_ports {cmos_vsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_vsync}]
set_property PACKAGE_PIN L16 [get_ports {cmos_pwdn}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_pwdn}]
set_property PACKAGE_PIN L19 [get_ports {cmos_rst}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_rst}]
set_property PACKAGE_PIN M17 [get_ports {cmos_db[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_db[7]}]
set_property PACKAGE_PIN P18 [get_ports {cmos_db[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_db[6]}]
set_property PACKAGE_PIN N20 [get_ports {cmos_db[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_db[5]}]
set_property PACKAGE_PIN M19 [get_ports {cmos_db[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_db[4]}]
set_property PACKAGE_PIN M20 [get_ports {cmos_db[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_db[3]}]
set_property PACKAGE_PIN L17 [get_ports {cmos_db[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_db[2]}]
set_property PACKAGE_PIN M18 [get_ports {cmos_db[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_db[1]}]
set_property PACKAGE_PIN L20 [get_ports {cmos_db[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_db[0]}]

set_property PACKAGE_PIN K19 [get_ports {rxd}]
set_property IOSTANDARD LVCMOS33 [get_ports {rxd}]
set_property PACKAGE_PIN J20 [get_ports {txd}]
set_property IOSTANDARD LVCMOS33 [get_ports {txd}]

set_property PACKAGE_PIN K18 [get_ports {audio_r}]
set_property IOSTANDARD LVCMOS33 [get_ports {audio_r}]
set_property PACKAGE_PIN J19 [get_ports {audio_l}]
set_property IOSTANDARD LVCMOS33 [get_ports {audio_l}]

set_property PACKAGE_PIN G19 [get_ports {vga_hs}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_hs}]
set_property PACKAGE_PIN H20 [get_ports {vga_vs}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_vs}]
set_property PACKAGE_PIN G20 [get_ports {vgad[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgad[0]}]
set_property PACKAGE_PIN J18 [get_ports {vgad[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgad[1]}]
set_property PACKAGE_PIN F19 [get_ports {vgad[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgad[2]}]
set_property PACKAGE_PIN K17 [get_ports {vgad[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgad[3]}]
set_property PACKAGE_PIN F20 [get_ports {vgad[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgad[4]}]
set_property PACKAGE_PIN E19 [get_ports {vgad[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgad[5]}]
set_property PACKAGE_PIN H18 [get_ports {vgad[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgad[6]}]
set_property PACKAGE_PIN D19 [get_ports {vgad[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgad[7]}]
set_property PACKAGE_PIN D20 [get_ports {vgad[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgad[8]}]
set_property PACKAGE_PIN D18 [get_ports {vgad[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgad[9]}]
set_property PACKAGE_PIN H17 [get_ports {vgad[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgad[10]}]
set_property PACKAGE_PIN C20 [get_ports {vgad[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgad[11]}]
set_property PACKAGE_PIN B19 [get_ports {vgad[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgad[12]}]
set_property PACKAGE_PIN B20 [get_ports {vgad[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgad[13]}]
set_property PACKAGE_PIN A20 [get_ports {vgad[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgad[14]}]
set_property PACKAGE_PIN H16 [get_ports {vgad[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgad[15]}]

########################################################################
### EBAZ4205  pin
########################################################################
set_property PACKAGE_PIN W13 [get_ports {led_r}]
set_property PACKAGE_PIN W14 [get_ports {led_g}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_r}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_g}]
set_property PACKAGE_PIN W15 [get_ports {mdio_rtl_0_mdc}]
set_property PACKAGE_PIN Y14 [get_ports {mdio_rtl_0_mdio_io}]
set_property PACKAGE_PIN U14 [get_ports {mii_rtl_0_rx_clk}]
set_property PACKAGE_PIN W16 [get_ports {mii_rtl_0_rx_dv}]
set_property PACKAGE_PIN Y16 [get_ports {mii_rtl_0_rxd[0]}]
set_property PACKAGE_PIN V16 [get_ports {mii_rtl_0_rxd[1]}]
set_property PACKAGE_PIN V17 [get_ports {mii_rtl_0_rxd[2]}]
set_property PACKAGE_PIN Y17 [get_ports {mii_rtl_0_rxd[3]}]
set_property PACKAGE_PIN U15 [get_ports {mii_rtl_0_tx_clk}]
set_property PACKAGE_PIN W19 [get_ports {mii_rtl_0_tx_en}]
set_property PACKAGE_PIN W18 [get_ports {mii_rtl_0_txd[0]}]
set_property PACKAGE_PIN Y18 [get_ports {mii_rtl_0_txd[1]}]
set_property PACKAGE_PIN V18 [get_ports {mii_rtl_0_txd[2]}]
set_property PACKAGE_PIN Y19 [get_ports {mii_rtl_0_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mdio_rtl_0_mdc}]
set_property IOSTANDARD LVCMOS33 [get_ports {mdio_rtl_0_mdio_io}]
set_property IOSTANDARD LVCMOS33 [get_ports {mii_rtl_0_rx_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {mii_rtl_0_rx_dv}]
set_property IOSTANDARD LVCMOS33 [get_ports {mii_rtl_0_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mii_rtl_0_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mii_rtl_0_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mii_rtl_0_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mii_rtl_0_tx_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {mii_rtl_0_tx_en}]
set_property IOSTANDARD LVCMOS33 [get_ports {mii_rtl_0_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mii_rtl_0_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mii_rtl_0_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mii_rtl_0_txd[3]}]
########################################################################
### other constraint
########################################################################

